### PR TITLE
added reference for docsify-darklight-theme under themes section

### PR DESCRIPTION
**Pull request by boopathikumar018**
added reference for docsify-darklight-theme under themes section

### CODE REVIEW

**Comment by jthegedus** [comment]
LGTM, though I cannot see the "theme switcher" in your preview 🤔

**Comment by boopathikumar018** [comment]
Hi @jthegedus , This is the expected output

### Dark view

image

### Light View

image


if you still faceing issue kindly let me know which browser and it version you are checking, so I can take it as an issue and fix

**Comment by anikethsaha** [comment]
even I couldn't see the switcher. 
```
chrome
Version 80.0.3987.149 (Official Build) (64-bit)
```

**Comment by jthegedus** [comment]
I cannot see it on:
- `FF Developer 75.0b7 (64-bit)`
- `FF 74.0 (64-bit)`
- `Brave v 1.5.112`

**Comment by boopathikumar018** [comment]
Can any one check now. I have tested with many browsers in different devices. Still you facing the issue try once in private mode if its persist let me know, so I can change the way of showing icons.  Thanks

**Comment by anikethsaha** [comment]
stll same

**Comment by boopathikumar018** [comment]
[docsify-darklight-theme](https://github.com/boopathikumar018/docsify-darklight-theme)  is the correct repo. [Docs | preview](https://boopathikumar018.github.io/docsify-darklight-theme/)

**Comment by jthegedus** [comment]
Worked for me in a private tab

**Comment by boopathikumar018** [comment]
If all good approve my PR

**Comment by anikethsaha** [comment]
I still cant see the switcher on your website. 
Please fix that. cause the whole purpose of your library is to have a dark mode with the switcher and its not visible I dont think we can add it. I don't know why it's visible to only the private tab or something else. Even I couldn't see the source code in your repo, its just the build on.
In the meantime, I am adding `Do no merge` and `WIP` label.

take your time and fix it and let us know, we will merge this. 👍 

Thanks

**Comment by boopathikumar018** [comment]
Hi @anikethsaha  thanks for your time to validate my PR. I updated my  `.gitignore` which was wrongly updated while copy pasting from `.npmignore` and I did't noticed that. Now the code was pushed to my public git repo.

The reason why it is working in private mode means, may my previous version store wrong value in cookie and served same from cache till now. That's why I asked to check in private mode.

Now you have my code on git . Feel free to pull and check locally. I suggest you to clear the browser cache once before testing it locally.

If you find any issues let me know so I can fix it. Thanks

**Comment by boopathikumar018** [comment]
Sure thanks for your time ✌🏻

**Comment by jthegedus** [comment]
Works for me without a private window.

**Pull request merged**
