### PR TITLE
ci: migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by jthegedus**
Replace CircleCI with GitHub Actions (aligning with core docsify repo) using [jthegedus/github-action-awesome-lint](https://github.com/jthegedus/github-action-awesome-lint) Action

### CODE REVIEW

**Comment by anikethsaha** [comment]
remove circle CI

**Comment by jthegedus** [comment]
@anikethsaha I do not have Admin permissions in CircleCI to un-link the `awesome-docsify` repo from the product. Do you happen to have access?

**Comment by anikethsaha** [comment]
delete the `,circle` folder. I guess it will work

**Comment by jthegedus** [comment]
I believe I have deleted it. The job is failing because it cannot find a config

**Comment by jthegedus** [comment]
I do not have permissions to remove the repo from CircleCI.

image

**Comment by anikethsaha** [comment]
> I believe I have deleted it. The job is failing because it cannot find a config

Ohh...sorry I was checking the master branch 😁 

No I dont have the access for it.

Let me contact the owner of docsify and I will get back to you

**Comment by jthegedus** [comment]
Cheers mate, merge at your leisure.

**Comment by jthegedus** [comment]
I also updated the branch protections to require review and ci passes

image

**Pull request merged**
