### PR TITLE
Add docsify-latex to plugin list

### PR DESCRIPTION
**Pull request by scruel**

### CODE REVIEW

**Comment by Koooooo-7** [comment]
Hi @scruel ,  could u plz get this plugin with more clear documents firstly? It will make users it handily.

**Comment by scruel** [comment]
> Hi @scruel , could u plz get this plugin with more clear documents firstly? It will make users it handily.

Sure, I am writing docs and keep testing it, might will be completed within 2 days.

**Comment by scruel** [comment]
@Koooooo-7 https://scruel.github.io/docsify-latex/

**Comment by scruel** [comment]
Hi, documentation is here:
https://scruel.github.io/docsify-latex/

**Comment by Koooooo-7** [comment]
> Hi, documentation is here: https://scruel.github.io/docsify-latex/

nice job!

**Review by Koooooo-7 — APPROVED** [review]
LGTM.

**Pull request merged**
