### PR TITLE
Add `google-spreadsheet` to showcase

### PR DESCRIPTION
**Pull request by theoephraim**
Adding my docs site to the showcase. I think I did some particularly nice stuff with the code docs :)

### CODE REVIEW

**Comment by jthegedus** [comment]
It is very nice indeed :)

**Comment by theoephraim** [comment]
Hm it says I'm missing the proper punctuation but not sure why as there is a period?

**Comment by jthegedus** [comment]
It is referring to line 104 which was not touched by you, so not your fault. Nonetheless, can you fix it?

**Comment by theoephraim** [comment]
Ah - wasn't even reading. Cheers!

**Comment by jthegedus** [comment]
Thanks mate, sorry for the inconvenience :)

**Pull request merged**
