### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sunhailin-Leo**
* Add `pyecharts` and `gallery-pyecharts`

### CODE REVIEW

**Comment by anikethsaha** [comment]
fix the linting issues and then we are good to go 👍

**Comment by sunhailin-Leo** [comment]
@anikethsaha 
* The linting problem seems about the badge icon.
image

**Comment by anikethsaha** [comment]
Can you fix it if possible?

**Comment by sunhailin-Leo** [comment]
@anikethsaha 
* Should I replace `%20` to empty space?

**Comment by sunhailin-Leo** [comment]
I think the `awesome-lint` have some error when processing the URL with URL Encode.

**Comment by anikethsaha** [comment]
cc @jthegedus any input ?

**Comment by anikethsaha** [comment]
@sunhailin-Leo ok...we can fix those issue in separate PR . 👍

**Comment by jthegedus** [comment]
No idea why that is failing, will fix today

**Pull request merged**
